#Project Setup
general:
  unsafeMode: false
  projectName: 'cloud-cap-sfems-bp'
  productiveBranch: 'master'

### Step-specific configuration
steps:
  artifactPrepareVersion:
    buildTool: 'mta'
  npmExecute:
    dockerImage: 'ppiper/node-browsers:v2'
  cloudFoundryDeploy:
    dockerImage: 'ppiper/cf-cli'
    mtaDeployParameters: '-f --version-rule ALL'
  sapNexusStage:
    stagingProfile: 'integration'
    repositoryFormat: 'npm'
  sapNexusUploadArtifacts:
    packaging: 'mtar'
    buildDescriptorFile: 'mta.yaml'
    uploadFile: 'cloud-sf-extension-cap-sample_1.0.0.mtar'
    artifactType: 'mta'
  mtaBuild:
    mtaBuildTool: "cloudMbt"


### Stage-specific configuration
stages:
  npmAudit:
    auditedAdvisories:
    # high
      - 550  
      - 593
      - 1184
      - 755
      - 1065
      - 1164
      - 1316
      - 1324
      - 1325
    # moderate
      - 535
      - 1300
 
  lint:
    ui5BestPractices:
      failThreshold:
        error: 100
        warning: 500
        info: 1000
       
  productionDeployment:
    cfTargets:
      - org:  'SFSubdomain'
        space: 'dev'
        appName: 'cloud-sf-extension-cap-sample'
        apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
        credentialsId: 'cf-credentails'
